/**
 * Alert class represents a medical alert generated by the system
 */
public class Alert {
    private String alertId;
    private String message;
    private static int alertCounter = 1;
    
    public Alert(String message) {
        this.alertId = "ALERT-" + alertCounter++;
        this.message = message;
    }
    
    public void sendAlert() {
        System.out.println("🚨 ALERT " + alertId + ": " + message);
    }
    
    public String getMessage() {
        return message;
    }
    
    public String getAlertId() {
        return alertId;
    }
}